services:
  web:
    image: frikshun/sentiment_analyzer:latest
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - DATABASE_URL=sqlite3:/app/db/production.sqlite3
      - SECRET_KEY_BASE=development_secret_key_base_for_docker_only_change_in_production
      - OPENAI_API_KEY=XXXXXX
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - ./db:app/db
      - ./storage:/app/storage
      - ./log:/app/log
   depends_on:
     - selenium

selenium:
  image: seleniarm/standalone-chromium:latest
  ports:
    - "4444:4444"
volumes:
  db_data:
